# -*- coding: utf-8 -*-

from typing import Final

# --------------------------------------------------------------------------------------
# fmt: off

# ASCII Control Characters (0-31)
NUL: Final[int] = 0    # 0x00 | Null character
SOH: Final[int] = 1    # 0x01 | Start of Heading
STX: Final[int] = 2    # 0x02 | Start of Text
ETX: Final[int] = 3    # 0x03 | End of Text
EOT: Final[int] = 4    # 0x04 | End of Transmission
ENQ: Final[int] = 5    # 0x05 | Enquiry
ACK: Final[int] = 6    # 0x06 | Acknowledgment
BEL: Final[int] = 7    # 0x07 | Bell
BS: Final[int] = 8     # 0x08 | Backspace
HT: Final[int] = 9     # 0x09 | Horizontal Tab
LF: Final[int] = 10    # 0x0A | Line Feed
VT: Final[int] = 11    # 0x0B | Vertical Tab
FF: Final[int] = 12    # 0x0C | Form Feed
CR: Final[int] = 13    # 0x0D | Carriage Return
SO: Final[int] = 14    # 0x0E | Shift Out
SI: Final[int] = 15    # 0x0F | Shift In
DLE: Final[int] = 16   # 0x10 | Data Link Escape
DC1: Final[int] = 17   # 0x11 | Device Control 1
DC2: Final[int] = 18   # 0x12 | Device Control 2
DC3: Final[int] = 19   # 0x13 | Device Control 3
DC4: Final[int] = 20   # 0x14 | Device Control 4
NAK: Final[int] = 21   # 0x15 | Negative Acknowledgment
SYN: Final[int] = 22   # 0x16 | Synchronous Idle
ETB: Final[int] = 23   # 0x17 | End of Transmission Block
CAN: Final[int] = 24   # 0x18 | Cancel
EM: Final[int] = 25    # 0x19 | End of Medium
SUB: Final[int] = 26   # 0x1A | Substitute
ESC: Final[int] = 27   # 0x1B | Escape
FS: Final[int] = 28    # 0x1C | File Separator
GS: Final[int] = 29    # 0x1D | Group Separator
RS: Final[int] = 30    # 0x1E | Record Separator
US: Final[int] = 31    # 0x1F | Unit Separator

# ASCII Printable Characters (32-126)
SPACE: Final[int] = 32                      # 0x20 | [SPACE]
EXCLAMATION_MARK: Final[int] = 33           # 0x21 | !
QUOTATION_MARK: Final[int] = 34             # 0x22 | "
NUMBER_SIGN: Final[int] = 35                # 0x23 | #
DOLLAR_SIGN: Final[int] = 36                # 0x24 | $
PERCENT_SIGN: Final[int] = 37               # 0x25 | %
AMPERSAND: Final[int] = 38                  # 0x26 | &
APOSTROPHE: Final[int] = 39                 # 0x27 | '
LEFT_PARENTHESIS: Final[int] = 40           # 0x28 | (
RIGHT_PARENTHESIS: Final[int] = 41          # 0x29 | )
ASTERISK: Final[int] = 42                   # 0x2A | *
PLUS_SIGN: Final[int] = 43                  # 0x2B | +
COMMA: Final[int] = 44                      # 0x2C | ,
HYPHEN_MINUS: Final[int] = 45               # 0x2D | -
FULL_STOP: Final[int] = 46                  # 0x2E | .
SOLIDUS: Final[int] = 47                    # 0x2F | /
DIGIT_ZERO: Final[int] = 48                 # 0x30 | 0
DIGIT_ONE: Final[int] = 49                  # 0x31 | 1
DIGIT_TWO: Final[int] = 50                  # 0x32 | 2
DIGIT_THREE: Final[int] = 51                # 0x33 | 3
DIGIT_FOUR: Final[int] = 52                 # 0x34 | 4
DIGIT_FIVE: Final[int] = 53                 # 0x35 | 5
DIGIT_SIX: Final[int] = 54                  # 0x36 | 6
DIGIT_SEVEN: Final[int] = 55                # 0x37 | 7
DIGIT_EIGHT: Final[int] = 56                # 0x38 | 8
DIGIT_NINE: Final[int] = 57                 # 0x39 | 9
COLON: Final[int] = 58                      # 0x3A | :
SEMICOLON: Final[int] = 59                  # 0x3B | ;
LESS_THAN_SIGN: Final[int] = 60             # 0x3C | <
EQUALS_SIGN: Final[int] = 61                # 0x3D | =
GREATER_THAN_SIGN: Final[int] = 62          # 0x3E | >
QUESTION_MARK: Final[int] = 63              # 0x3F | ?
COMMERCIAL_AT: Final[int] = 64              # 0x40 | @
LATIN_CAPITAL_LETTER_A: Final[int] = 65     # 0x41 | A
LATIN_CAPITAL_LETTER_B: Final[int] = 66     # 0x42 | B
LATIN_CAPITAL_LETTER_C: Final[int] = 67     # 0x43 | C
LATIN_CAPITAL_LETTER_D: Final[int] = 68     # 0x44 | D
LATIN_CAPITAL_LETTER_E: Final[int] = 69     # 0x45 | E
LATIN_CAPITAL_LETTER_F: Final[int] = 70     # 0x46 | F
LATIN_CAPITAL_LETTER_G: Final[int] = 71     # 0x47 | G
LATIN_CAPITAL_LETTER_H: Final[int] = 72     # 0x48 | H
LATIN_CAPITAL_LETTER_I: Final[int] = 73     # 0x49 | I
LATIN_CAPITAL_LETTER_J: Final[int] = 74     # 0x4A | J
LATIN_CAPITAL_LETTER_K: Final[int] = 75     # 0x4B | K
LATIN_CAPITAL_LETTER_L: Final[int] = 76     # 0x4C | L
LATIN_CAPITAL_LETTER_M: Final[int] = 77     # 0x4D | M
LATIN_CAPITAL_LETTER_N: Final[int] = 78     # 0x4E | N
LATIN_CAPITAL_LETTER_O: Final[int] = 79     # 0x4F | O
LATIN_CAPITAL_LETTER_P: Final[int] = 80     # 0x50 | P
LATIN_CAPITAL_LETTER_Q: Final[int] = 81     # 0x51 | Q
LATIN_CAPITAL_LETTER_R: Final[int] = 82     # 0x52 | R
LATIN_CAPITAL_LETTER_S: Final[int] = 83     # 0x53 | S
LATIN_CAPITAL_LETTER_T: Final[int] = 84     # 0x54 | T
LATIN_CAPITAL_LETTER_U: Final[int] = 85     # 0x55 | U
LATIN_CAPITAL_LETTER_V: Final[int] = 86     # 0x56 | V
LATIN_CAPITAL_LETTER_W: Final[int] = 87     # 0x57 | W
LATIN_CAPITAL_LETTER_X: Final[int] = 88     # 0x58 | X
LATIN_CAPITAL_LETTER_Y: Final[int] = 89     # 0x59 | Y
LATIN_CAPITAL_LETTER_Z: Final[int] = 90     # 0x5A | Z
LEFT_SQUARE_BRACKET: Final[int] = 91        # 0x5B | [
REVERSE_SOLIDUS: Final[int] = 92            # 0x5C | \
RIGHT_SQUARE_BRACKET: Final[int] = 93       # 0x5D | ]
CIRCUMFLEX_ACCENT: Final[int] = 94          # 0x5E | ^
LOW_LINE: Final[int] = 95                   # 0x5F | _
GRAVE_ACCENT: Final[int] = 96               # 0x60 | `
LATIN_SMALL_LETTER_A: Final[int] = 97       # 0x61 | a
LATIN_SMALL_LETTER_B: Final[int] = 98       # 0x62 | b
LATIN_SMALL_LETTER_C: Final[int] = 99       # 0x63 | c
LATIN_SMALL_LETTER_D: Final[int] = 100      # 0x64 | d
LATIN_SMALL_LETTER_E: Final[int] = 101      # 0x65 | e
LATIN_SMALL_LETTER_F: Final[int] = 102      # 0x66 | f
LATIN_SMALL_LETTER_G: Final[int] = 103      # 0x67 | g
LATIN_SMALL_LETTER_H: Final[int] = 104      # 0x68 | h
LATIN_SMALL_LETTER_I: Final[int] = 105      # 0x69 | i
LATIN_SMALL_LETTER_J: Final[int] = 106      # 0x6A | j
LATIN_SMALL_LETTER_K: Final[int] = 107      # 0x6B | k
LATIN_SMALL_LETTER_L: Final[int] = 108      # 0x6C | l
LATIN_SMALL_LETTER_M: Final[int] = 109      # 0x6D | m
LATIN_SMALL_LETTER_N: Final[int] = 110      # 0x6E | n
LATIN_SMALL_LETTER_O: Final[int] = 111      # 0x6F | o
LATIN_SMALL_LETTER_P: Final[int] = 112      # 0x70 | p
LATIN_SMALL_LETTER_Q: Final[int] = 113      # 0x71 | q
LATIN_SMALL_LETTER_R: Final[int] = 114      # 0x72 | r
LATIN_SMALL_LETTER_S: Final[int] = 115      # 0x73 | s
LATIN_SMALL_LETTER_T: Final[int] = 116      # 0x74 | t
LATIN_SMALL_LETTER_U: Final[int] = 117      # 0x75 | u
LATIN_SMALL_LETTER_V: Final[int] = 118      # 0x76 | v
LATIN_SMALL_LETTER_W: Final[int] = 119      # 0x77 | w
LATIN_SMALL_LETTER_X: Final[int] = 120      # 0x78 | x
LATIN_SMALL_LETTER_Y: Final[int] = 121      # 0x79 | y
LATIN_SMALL_LETTER_Z: Final[int] = 122      # 0x7A | z
LEFT_CURLY_BRACKET: Final[int] = 123        # 0x7B | {
VERTICAL_LINE: Final[int] = 124             # 0x7C | |
RIGHT_CURLY_BRACKET: Final[int] = 125       # 0x7D | }
TILDE: Final[int] = 126                     # 0x7E | ~

# ASCII Delete Character
DEL: Final[int] = 127

# Extended ASCII Characters (128-255) - Windows-1252 Encoding
EURO_SIGN: Final[int] = 128                                     # €
UNDEFINED_129: Final[int] = 129                                 # [UNDEFINED]
SINGLE_LOW_9_QUOTATION_MARK: Final[int] = 130                   # ‚
LATIN_SMALL_LETTER_F_WITH_HOOK: Final[int] = 131                # ƒ
DOUBLE_LOW_9_QUOTATION_MARK: Final[int] = 132                   # „
HORIZONTAL_ELLIPSIS: Final[int] = 133                           # …
DAGGER: Final[int] = 134                                        # †
DOUBLE_DAGGER: Final[int] = 135                                 # ‡
MODIFIER_LETTER_CIRCUMFLEX_ACCENT: Final[int] = 136             # ˆ
PER_MILLE_SIGN: Final[int] = 137                                # ‰
LATIN_CAPITAL_LETTER_S_WITH_CARON: Final[int] = 138             # Š
SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK: Final[int] = 139     # ‹
LATIN_CAPITAL_LIGATURE_OE: Final[int] = 140                     # Œ
UNDEFINED_141: Final[int] = 141                                 # [UNDEFINED]
LATIN_CAPITAL_LETTER_Z_WITH_CARON: Final[int] = 142             # Ž
UNDEFINED_143: Final[int] = 143                                 # [UNDEFINED]
UNDEFINED_144: Final[int] = 144                                 # [UNDEFINED]
LEFT_SINGLE_QUOTATION_MARK: Final[int] = 145                    # '
RIGHT_SINGLE_QUOTATION_MARK: Final[int] = 146                   # '
LEFT_DOUBLE_QUOTATION_MARK: Final[int] = 147                    # "
RIGHT_DOUBLE_QUOTATION_MARK: Final[int] = 148                   # "
BULLET: Final[int] = 149                                        # •
EN_DASH: Final[int] = 150                                       # –
EM_DASH: Final[int] = 151                                       # —
SMALL_TILDE: Final[int] = 152                                   # ˜
TRADE_MARK_SIGN: Final[int] = 153                               # ™
LATIN_SMALL_LETTER_S_WITH_CARON: Final[int] = 154               # š
SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK: Final[int] = 155    # ›
LATIN_SMALL_LIGATURE_OE: Final[int] = 156                       # œ
UNDEFINED_157: Final[int] = 157                                 # [UNDEFINED]
LATIN_SMALL_LETTER_Z_WITH_CARON: Final[int] = 158               # ž
LATIN_CAPITAL_LETTER_Y_WITH_DIAERESIS: Final[int] = 159         # Ÿ
NON_BREAK_SPACE: Final[int] = 160                               # [NBSP]
INVERTED_EXCLAMATION_MARK: Final[int] = 161                     # ¡
CENT_SIGN: Final[int] = 162                                     # ¢
POUND_SIGN: Final[int] = 163                                    # £
CURRENCY_SIGN: Final[int] = 164                                 # ¤
YEN_SIGN: Final[int] = 165                                      # ¥
BROKEN_BAR: Final[int] = 166                                    # ¦
SECTION_SIGN: Final[int] = 167                                  # §
DIAERESIS: Final[int] = 168                                     # ¨
COPYRIGHT_SIGN: Final[int] = 169                                # ©
FEMININE_ORDINAL_INDICATOR: Final[int] = 170                    # ª
LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK: Final[int] = 171     # «
NOT_SIGN: Final[int] = 172                                      # ¬
SOFT_HYPHEN: Final[int] = 173                                   # [SHY]
REGISTERED_SIGN: Final[int] = 174                               # ®
MACRON: Final[int] = 175                                        # ¯
DEGREE_SIGN: Final[int] = 176                                   # °
PLUS_MINUS_SIGN: Final[int] = 177                               # ±
SUPERSCRIPT_TWO: Final[int] = 178                               # ²
SUPERSCRIPT_THREE: Final[int] = 179                             # ³
ACUTE_ACCENT: Final[int] = 180                                  # ´
MICRO_SIGN: Final[int] = 181                                    # µ
PILCROW_SIGN: Final[int] = 182                                  # ¶
MIDDLE_DOT: Final[int] = 183                                    # ·
CEDILLA: Final[int] = 184                                       # ¸
SUPERSCRIPT_ONE: Final[int] = 185                               # ¹
MASCULINE_ORDINAL_INDICATOR: Final[int] = 186                   # º
RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK: Final[int] = 187    # »
VULGAR_FRACTION_ONE_QUARTER: Final[int] = 188                   # ¼
VULGAR_FRACTION_ONE_HALF: Final[int] = 189                      # ½
VULGAR_FRACTION_THREE_QUARTERS: Final[int] = 190                # ¾
INVERTED_QUESTION_MARK: Final[int] = 191                        # ¿
LATIN_CAPITAL_LETTER_A_WITH_GRAVE: Final[int] = 192             # À
LATIN_CAPITAL_LETTER_A_WITH_ACUTE: Final[int] = 193             # Á
LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX: Final[int] = 194        # Â
LATIN_CAPITAL_LETTER_A_WITH_TILDE: Final[int] = 195             # Ã
LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS: Final[int] = 196         # Ä
LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE: Final[int] = 197        # Å
LATIN_CAPITAL_LETTER_AE: Final[int] = 198                       # Æ
LATIN_CAPITAL_LETTER_C_WITH_CEDILLA: Final[int] = 199           # Ç
LATIN_CAPITAL_LETTER_E_WITH_GRAVE: Final[int] = 200             # È
LATIN_CAPITAL_LETTER_E_WITH_ACUTE: Final[int] = 201             # É
LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX: Final[int] = 202        # Ê
LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS: Final[int] = 203         # Ë
LATIN_CAPITAL_LETTER_I_WITH_GRAVE: Final[int] = 204             # Ì
LATIN_CAPITAL_LETTER_I_WITH_ACUTE: Final[int] = 205             # Í
LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX: Final[int] = 206        # Î
LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS: Final[int] = 207         # Ï
LATIN_CAPITAL_LETTER_ETH: Final[int] = 208                      # Ð
LATIN_CAPITAL_LETTER_N_WITH_TILDE: Final[int] = 209             # Ñ
LATIN_CAPITAL_LETTER_O_WITH_GRAVE: Final[int] = 210             # Ò
LATIN_CAPITAL_LETTER_O_WITH_ACUTE: Final[int] = 211             # Ó
LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX: Final[int] = 212        # Ô
LATIN_CAPITAL_LETTER_O_WITH_TILDE: Final[int] = 213             # Õ
LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS: Final[int] = 214         # Ö
MULTIPLICATION_SIGN: Final[int] = 215                           # ×
LATIN_CAPITAL_LETTER_O_WITH_STROKE: Final[int] = 216            # Ø
LATIN_CAPITAL_LETTER_U_WITH_GRAVE: Final[int] = 217             # Ù
LATIN_CAPITAL_LETTER_U_WITH_ACUTE: Final[int] = 218             # Ú
LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX: Final[int] = 219        # Û
LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS: Final[int] = 220         # Ü
LATIN_CAPITAL_LETTER_Y_WITH_ACUTE: Final[int] = 221             # Ý
LATIN_CAPITAL_LETTER_THORN: Final[int] = 222                    # Þ
LATIN_SMALL_LETTER_SHARP_S: Final[int] = 223                    # ß
LATIN_SMALL_LETTER_A_WITH_GRAVE: Final[int] = 224               # à
LATIN_SMALL_LETTER_A_WITH_ACUTE: Final[int] = 225               # á
LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX: Final[int] = 226          # â
LATIN_SMALL_LETTER_A_WITH_TILDE: Final[int] = 227               # ã
LATIN_SMALL_LETTER_A_WITH_DIAERESIS: Final[int] = 228           # ä
LATIN_SMALL_LETTER_A_WITH_RING_ABOVE: Final[int] = 229          # å
LATIN_SMALL_LETTER_AE: Final[int] = 230                         # æ
LATIN_SMALL_LETTER_C_WITH_CEDILLA: Final[int] = 231             # ç
LATIN_SMALL_LETTER_E_WITH_GRAVE: Final[int] = 232               # è
LATIN_SMALL_LETTER_E_WITH_ACUTE: Final[int] = 233               # é
LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX: Final[int] = 234          # ê
LATIN_SMALL_LETTER_E_WITH_DIAERESIS: Final[int] = 235           # ë
LATIN_SMALL_LETTER_I_WITH_GRAVE: Final[int] = 236               # ì
LATIN_SMALL_LETTER_I_WITH_ACUTE: Final[int] = 237               # í
LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX: Final[int] = 238          # î
LATIN_SMALL_LETTER_I_WITH_DIAERESIS: Final[int] = 239           # ï
LATIN_SMALL_LETTER_ETH: Final[int] = 240                        # ð
LATIN_SMALL_LETTER_N_WITH_TILDE: Final[int] = 241               # ñ
LATIN_SMALL_LETTER_O_WITH_GRAVE: Final[int] = 242               # ò
LATIN_SMALL_LETTER_O_WITH_ACUTE: Final[int] = 243               # ó
LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX: Final[int] = 244          # ô
LATIN_SMALL_LETTER_O_WITH_TILDE: Final[int] = 245               # õ
LATIN_SMALL_LETTER_O_WITH_DIAERESIS: Final[int] = 246           # ö
DIVISION_SIGN: Final[int] = 247                                 # ÷
LATIN_SMALL_LETTER_O_WITH_STROKE: Final[int] = 248              # ø
LATIN_SMALL_LETTER_U_WITH_GRAVE: Final[int] = 249               # ù
LATIN_SMALL_LETTER_U_WITH_ACUTE: Final[int] = 250               # ú
LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX: Final[int] = 251          # û
LATIN_SMALL_LETTER_U_WITH_DIAERESIS: Final[int] = 252           # ü
LATIN_SMALL_LETTER_Y_WITH_ACUTE: Final[int] = 253               # ý
LATIN_SMALL_LETTER_THORN: Final[int] = 254                      # þ
LATIN_SMALL_LETTER_Y_WITH_DIAERESIS: Final[int] = 255           # ÿ

# fmt: on
# --------------------------------------------------------------------------------------
