# -*- coding: utf-8 -*-

from typing import Final

# --------------------------------------------------------------------------------------
# fmt: off

# ASCII Control Characters (0-31)
NUL: Final[int] = 0    # Null character
SOH: Final[int] = 1    # Start of Heading
STX: Final[int] = 2    # Start of Text
ETX: Final[int] = 3    # End of Text
EOT: Final[int] = 4    # End of Transmission
ENQ: Final[int] = 5    # Enquiry
ACK: Final[int] = 6    # Acknowledgment
BEL: Final[int] = 7    # Bell
BS: Final[int] = 8     # Backspace
HT: Final[int] = 9     # Horizontal Tab
LF: Final[int] = 10    # Line Feed
VT: Final[int] = 11    # Vertical Tab
FF: Final[int] = 12    # Form Feed
CR: Final[int] = 13    # Carriage Return
SO: Final[int] = 14    # Shift Out
SI: Final[int] = 15    # Shift In
DLE: Final[int] = 16   # Data Link Escape
DC1: Final[int] = 17   # Device Control 1
DC2: Final[int] = 18   # Device Control 2
DC3: Final[int] = 19   # Device Control 3
DC4: Final[int] = 20   # Device Control 4
NAK: Final[int] = 21   # Negative Acknowledgment
SYN: Final[int] = 22   # Synchronous Idle
ETB: Final[int] = 23   # End of Transmission Block
CAN: Final[int] = 24   # Cancel
EM: Final[int] = 25    # End of Medium
SUB: Final[int] = 26   # Substitute
ESC: Final[int] = 27   # Escape
FS: Final[int] = 28    # File Separator
GS: Final[int] = 29    # Group Separator
RS: Final[int] = 30    # Record Separator
US: Final[int] = 31    # Unit Separator

# ASCII Printable Characters (32-126)
SPACE: Final[int] = 32                      # [SPACE]
EXCLAMATION_MARK: Final[int] = 33           # !
QUOTATION_MARK: Final[int] = 34             # "
NUMBER_SIGN: Final[int] = 35                # #
DOLLAR_SIGN: Final[int] = 36                # $
PERCENT_SIGN: Final[int] = 37               # %
AMPERSAND: Final[int] = 38                  # &
APOSTROPHE: Final[int] = 39                 # '
LEFT_PARENTHESIS: Final[int] = 40           # (
RIGHT_PARENTHESIS: Final[int] = 41          # )
ASTERISK: Final[int] = 42                   # *
PLUS_SIGN: Final[int] = 43                  # +
COMMA: Final[int] = 44                      # ,
HYPHEN_MINUS: Final[int] = 45               # -
FULL_STOP: Final[int] = 46                  # .
SOLIDUS: Final[int] = 47                    # /
DIGIT_ZERO: Final[int] = 48                 # 0
DIGIT_ONE: Final[int] = 49                  # 1
DIGIT_TWO: Final[int] = 50                  # 2
DIGIT_THREE: Final[int] = 51                # 3
DIGIT_FOUR: Final[int] = 52                 # 4
DIGIT_FIVE: Final[int] = 53                 # 5
DIGIT_SIX: Final[int] = 54                  # 6
DIGIT_SEVEN: Final[int] = 55                # 7
DIGIT_EIGHT: Final[int] = 56                # 8
DIGIT_NINE: Final[int] = 57                 # 9
COLON: Final[int] = 58                      # :
SEMICOLON: Final[int] = 59                  # ;
LESS_THAN_SIGN: Final[int] = 60             # <
EQUALS_SIGN: Final[int] = 61                # =
GREATER_THAN_SIGN: Final[int] = 62          # >
QUESTION_MARK: Final[int] = 63              # ?
COMMERCIAL_AT: Final[int] = 64              # @
LATIN_CAPITAL_LETTER_A: Final[int] = 65     # A
LATIN_CAPITAL_LETTER_B: Final[int] = 66     # B
LATIN_CAPITAL_LETTER_C: Final[int] = 67     # C
LATIN_CAPITAL_LETTER_D: Final[int] = 68     # D
LATIN_CAPITAL_LETTER_E: Final[int] = 69     # E
LATIN_CAPITAL_LETTER_F: Final[int] = 70     # F
LATIN_CAPITAL_LETTER_G: Final[int] = 71     # G
LATIN_CAPITAL_LETTER_H: Final[int] = 72     # H
LATIN_CAPITAL_LETTER_I: Final[int] = 73     # I
LATIN_CAPITAL_LETTER_J: Final[int] = 74     # J
LATIN_CAPITAL_LETTER_K: Final[int] = 75     # K
LATIN_CAPITAL_LETTER_L: Final[int] = 76     # L
LATIN_CAPITAL_LETTER_M: Final[int] = 77     # M
LATIN_CAPITAL_LETTER_N: Final[int] = 78     # N
LATIN_CAPITAL_LETTER_O: Final[int] = 79     # O
LATIN_CAPITAL_LETTER_P: Final[int] = 80     # P
LATIN_CAPITAL_LETTER_Q: Final[int] = 81     # Q
LATIN_CAPITAL_LETTER_R: Final[int] = 82     # R
LATIN_CAPITAL_LETTER_S: Final[int] = 83     # S
LATIN_CAPITAL_LETTER_T: Final[int] = 84     # T
LATIN_CAPITAL_LETTER_U: Final[int] = 85     # U
LATIN_CAPITAL_LETTER_V: Final[int] = 86     # V
LATIN_CAPITAL_LETTER_W: Final[int] = 87     # W
LATIN_CAPITAL_LETTER_X: Final[int] = 88     # X
LATIN_CAPITAL_LETTER_Y: Final[int] = 89     # Y
LATIN_CAPITAL_LETTER_Z: Final[int] = 90     # Z
LEFT_SQUARE_BRACKET: Final[int] = 91        # [
REVERSE_SOLIDUS: Final[int] = 92            # \
RIGHT_SQUARE_BRACKET: Final[int] = 93       # ]
CIRCUMFLEX_ACCENT: Final[int] = 94          # ^
LOW_LINE: Final[int] = 95                   # _
GRAVE_ACCENT: Final[int] = 96               # `
LATIN_SMALL_LETTER_A: Final[int] = 97       # a
LATIN_SMALL_LETTER_B: Final[int] = 98       # b
LATIN_SMALL_LETTER_C: Final[int] = 99       # c
LATIN_SMALL_LETTER_D: Final[int] = 100      # d
LATIN_SMALL_LETTER_E: Final[int] = 101      # e
LATIN_SMALL_LETTER_F: Final[int] = 102      # f
LATIN_SMALL_LETTER_G: Final[int] = 103      # g
LATIN_SMALL_LETTER_H: Final[int] = 104      # h
LATIN_SMALL_LETTER_I: Final[int] = 105      # i
LATIN_SMALL_LETTER_J: Final[int] = 106      # j
LATIN_SMALL_LETTER_K: Final[int] = 107      # k
LATIN_SMALL_LETTER_L: Final[int] = 108      # l
LATIN_SMALL_LETTER_M: Final[int] = 109      # m
LATIN_SMALL_LETTER_N: Final[int] = 110      # n
LATIN_SMALL_LETTER_O: Final[int] = 111      # o
LATIN_SMALL_LETTER_P: Final[int] = 112      # p
LATIN_SMALL_LETTER_Q: Final[int] = 113      # q
LATIN_SMALL_LETTER_R: Final[int] = 114      # r
LATIN_SMALL_LETTER_S: Final[int] = 115      # s
LATIN_SMALL_LETTER_T: Final[int] = 116      # t
LATIN_SMALL_LETTER_U: Final[int] = 117      # u
LATIN_SMALL_LETTER_V: Final[int] = 118      # v
LATIN_SMALL_LETTER_W: Final[int] = 119      # w
LATIN_SMALL_LETTER_X: Final[int] = 120      # x
LATIN_SMALL_LETTER_Y: Final[int] = 121      # y
LATIN_SMALL_LETTER_Z: Final[int] = 122      # z
LEFT_CURLY_BRACKET: Final[int] = 123        # {
VERTICAL_LINE: Final[int] = 124             # |
RIGHT_CURLY_BRACKET: Final[int] = 125       # }
TILDE: Final[int] = 126                     # ~

# ASCII Delete Character
DEL: Final[int] = 127

# Extended ASCII Characters (128-255) - Windows-1252 Encoding
EURO_SIGN: Final[int] = 128                                     # €
UNDEFINED_129: Final[int] = 129                                 # [UNDEFINED]
SINGLE_LOW_9_QUOTATION_MARK: Final[int] = 130                   # ‚
LATIN_SMALL_LETTER_F_WITH_HOOK: Final[int] = 131                # ƒ
DOUBLE_LOW_9_QUOTATION_MARK: Final[int] = 132                   # „
HORIZONTAL_ELLIPSIS: Final[int] = 133                           # …
DAGGER: Final[int] = 134                                        # †
DOUBLE_DAGGER: Final[int] = 135                                 # ‡
MODIFIER_LETTER_CIRCUMFLEX_ACCENT: Final[int] = 136             # ˆ
PER_MILLE_SIGN: Final[int] = 137                                # ‰
LATIN_CAPITAL_LETTER_S_WITH_CARON: Final[int] = 138             # Š
SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK: Final[int] = 139     # ‹
LATIN_CAPITAL_LIGATURE_OE: Final[int] = 140                     # Œ
UNDEFINED_141: Final[int] = 141                                 # [UNDEFINED]
LATIN_CAPITAL_LETTER_Z_WITH_CARON: Final[int] = 142             # Ž
UNDEFINED_143: Final[int] = 143                                 # [UNDEFINED]
UNDEFINED_144: Final[int] = 144                                 # [UNDEFINED]
LEFT_SINGLE_QUOTATION_MARK: Final[int] = 145                    # '
RIGHT_SINGLE_QUOTATION_MARK: Final[int] = 146                   # '
LEFT_DOUBLE_QUOTATION_MARK: Final[int] = 147                    # "
RIGHT_DOUBLE_QUOTATION_MARK: Final[int] = 148                   # "
BULLET: Final[int] = 149                                        # •
EN_DASH: Final[int] = 150                                       # –
EM_DASH: Final[int] = 151                                       # —
SMALL_TILDE: Final[int] = 152                                   # ˜
TRADE_MARK_SIGN: Final[int] = 153                               # ™
LATIN_SMALL_LETTER_S_WITH_CARON: Final[int] = 154               # š
SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK: Final[int] = 155    # ›
LATIN_SMALL_LIGATURE_OE: Final[int] = 156                       # œ
UNDEFINED_157: Final[int] = 157                                 # [UNDEFINED]
LATIN_SMALL_LETTER_Z_WITH_CARON: Final[int] = 158               # ž
LATIN_CAPITAL_LETTER_Y_WITH_DIAERESIS: Final[int] = 159         # Ÿ
NON_BREAK_SPACE: Final[int] = 160                               # [NBSP]
INVERTED_EXCLAMATION_MARK: Final[int] = 161                     # ¡
CENT_SIGN: Final[int] = 162                                     # ¢
POUND_SIGN: Final[int] = 163                                    # £
CURRENCY_SIGN: Final[int] = 164                                 # ¤
YEN_SIGN: Final[int] = 165                                      # ¥
BROKEN_BAR: Final[int] = 166                                    # ¦
SECTION_SIGN: Final[int] = 167                                  # §
DIAERESIS: Final[int] = 168                                     # ¨
COPYRIGHT_SIGN: Final[int] = 169                                # ©
FEMININE_ORDINAL_INDICATOR: Final[int] = 170                    # ª
LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK: Final[int] = 171     # «
NOT_SIGN: Final[int] = 172                                      # ¬
SOFT_HYPHEN: Final[int] = 173                                   # [SHY]
REGISTERED_SIGN: Final[int] = 174                               # ®
MACRON: Final[int] = 175                                        # ¯
DEGREE_SIGN: Final[int] = 176                                   # °
PLUS_MINUS_SIGN: Final[int] = 177                               # ±
SUPERSCRIPT_TWO: Final[int] = 178                               # ²
SUPERSCRIPT_THREE: Final[int] = 179                             # ³
ACUTE_ACCENT: Final[int] = 180                                  # ´
MICRO_SIGN: Final[int] = 181                                    # µ
PILCROW_SIGN: Final[int] = 182                                  # ¶
MIDDLE_DOT: Final[int] = 183                                    # ·
CEDILLA: Final[int] = 184                                       # ¸
SUPERSCRIPT_ONE: Final[int] = 185                               # ¹
MASCULINE_ORDINAL_INDICATOR: Final[int] = 186                   # º
RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK: Final[int] = 187    # »
VULGAR_FRACTION_ONE_QUARTER: Final[int] = 188                   # ¼
VULGAR_FRACTION_ONE_HALF: Final[int] = 189                      # ½
VULGAR_FRACTION_THREE_QUARTERS: Final[int] = 190                # ¾
INVERTED_QUESTION_MARK: Final[int] = 191                        # ¿
LATIN_CAPITAL_LETTER_A_WITH_GRAVE: Final[int] = 192             # À
LATIN_CAPITAL_LETTER_A_WITH_ACUTE: Final[int] = 193             # Á
LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX: Final[int] = 194        # Â
LATIN_CAPITAL_LETTER_A_WITH_TILDE: Final[int] = 195             # Ã
LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS: Final[int] = 196         # Ä
LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE: Final[int] = 197        # Å
LATIN_CAPITAL_LETTER_AE: Final[int] = 198                       # Æ
LATIN_CAPITAL_LETTER_C_WITH_CEDILLA: Final[int] = 199           # Ç
LATIN_CAPITAL_LETTER_E_WITH_GRAVE: Final[int] = 200             # È
LATIN_CAPITAL_LETTER_E_WITH_ACUTE: Final[int] = 201             # É
LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX: Final[int] = 202        # Ê
LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS: Final[int] = 203         # Ë
LATIN_CAPITAL_LETTER_I_WITH_GRAVE: Final[int] = 204             # Ì
LATIN_CAPITAL_LETTER_I_WITH_ACUTE: Final[int] = 205             # Í
LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX: Final[int] = 206        # Î
LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS: Final[int] = 207         # Ï
LATIN_CAPITAL_LETTER_ETH: Final[int] = 208                      # Ð
LATIN_CAPITAL_LETTER_N_WITH_TILDE: Final[int] = 209             # Ñ
LATIN_CAPITAL_LETTER_O_WITH_GRAVE: Final[int] = 210             # Ò
LATIN_CAPITAL_LETTER_O_WITH_ACUTE: Final[int] = 211             # Ó
LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX: Final[int] = 212        # Ô
LATIN_CAPITAL_LETTER_O_WITH_TILDE: Final[int] = 213             # Õ
LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS: Final[int] = 214         # Ö
MULTIPLICATION_SIGN: Final[int] = 215                           # ×
LATIN_CAPITAL_LETTER_O_WITH_STROKE: Final[int] = 216            # Ø
LATIN_CAPITAL_LETTER_U_WITH_GRAVE: Final[int] = 217             # Ù
LATIN_CAPITAL_LETTER_U_WITH_ACUTE: Final[int] = 218             # Ú
LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX: Final[int] = 219        # Û
LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS: Final[int] = 220         # Ü
LATIN_CAPITAL_LETTER_Y_WITH_ACUTE: Final[int] = 221             # Ý
LATIN_CAPITAL_LETTER_THORN: Final[int] = 222                    # Þ
LATIN_SMALL_LETTER_SHARP_S: Final[int] = 223                    # ß
LATIN_SMALL_LETTER_A_WITH_GRAVE: Final[int] = 224               # à
LATIN_SMALL_LETTER_A_WITH_ACUTE: Final[int] = 225               # á
LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX: Final[int] = 226          # â
LATIN_SMALL_LETTER_A_WITH_TILDE: Final[int] = 227               # ã
LATIN_SMALL_LETTER_A_WITH_DIAERESIS: Final[int] = 228           # ä
LATIN_SMALL_LETTER_A_WITH_RING_ABOVE: Final[int] = 229          # å
LATIN_SMALL_LETTER_AE: Final[int] = 230                         # æ
LATIN_SMALL_LETTER_C_WITH_CEDILLA: Final[int] = 231             # ç
LATIN_SMALL_LETTER_E_WITH_GRAVE: Final[int] = 232               # è
LATIN_SMALL_LETTER_E_WITH_ACUTE: Final[int] = 233               # é
LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX: Final[int] = 234          # ê
LATIN_SMALL_LETTER_E_WITH_DIAERESIS: Final[int] = 235           # ë
LATIN_SMALL_LETTER_I_WITH_GRAVE: Final[int] = 236               # ì
LATIN_SMALL_LETTER_I_WITH_ACUTE: Final[int] = 237               # í
LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX: Final[int] = 238          # î
LATIN_SMALL_LETTER_I_WITH_DIAERESIS: Final[int] = 239           # ï
LATIN_SMALL_LETTER_ETH: Final[int] = 240                        # ð
LATIN_SMALL_LETTER_N_WITH_TILDE: Final[int] = 241               # ñ
LATIN_SMALL_LETTER_O_WITH_GRAVE: Final[int] = 242               # ò
LATIN_SMALL_LETTER_O_WITH_ACUTE: Final[int] = 243               # ó
LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX: Final[int] = 244          # ô
LATIN_SMALL_LETTER_O_WITH_TILDE: Final[int] = 245               # õ
LATIN_SMALL_LETTER_O_WITH_DIAERESIS: Final[int] = 246           # ö
DIVISION_SIGN: Final[int] = 247                                 # ÷
LATIN_SMALL_LETTER_O_WITH_STROKE: Final[int] = 248              # ø
LATIN_SMALL_LETTER_U_WITH_GRAVE: Final[int] = 249               # ù
LATIN_SMALL_LETTER_U_WITH_ACUTE: Final[int] = 250               # ú
LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX: Final[int] = 251          # û
LATIN_SMALL_LETTER_U_WITH_DIAERESIS: Final[int] = 252           # ü
LATIN_SMALL_LETTER_Y_WITH_ACUTE: Final[int] = 253               # ý
LATIN_SMALL_LETTER_THORN: Final[int] = 254                      # þ
LATIN_SMALL_LETTER_Y_WITH_DIAERESIS: Final[int] = 255           # ÿ

# fmt: on
# --------------------------------------------------------------------------------------
