# -*- coding: utf-8 -*-

from enum import IntEnum, unique
from typing import Final

from imgui_bundle import imgui


@unique
class ColorVar(IntEnum):
    text = imgui.Col_.text.value
    text_disabled = imgui.Col_.text_disabled.value
    window_bg = imgui.Col_.window_bg.value
    child_bg = imgui.Col_.child_bg.value
    popup_bg = imgui.Col_.popup_bg.value
    border = imgui.Col_.border.value
    border_shadow = imgui.Col_.border_shadow.value
    frame_bg = imgui.Col_.frame_bg.value
    frame_bg_hovered = imgui.Col_.frame_bg_hovered.value
    frame_bg_active = imgui.Col_.frame_bg_active.value
    title_bg = imgui.Col_.title_bg.value
    title_bg_active = imgui.Col_.title_bg_active.value
    title_bg_collapsed = imgui.Col_.title_bg_collapsed.value
    menu_bar_bg = imgui.Col_.menu_bar_bg.value
    scrollbar_bg = imgui.Col_.scrollbar_bg.value
    scrollbar_grab = imgui.Col_.scrollbar_grab.value
    scrollbar_grab_hovered = imgui.Col_.scrollbar_grab_hovered.value
    scrollbar_grab_active = imgui.Col_.scrollbar_grab_active.value
    check_mark = imgui.Col_.check_mark.value
    slider_grab = imgui.Col_.slider_grab.value
    slider_grab_active = imgui.Col_.slider_grab_active.value
    button = imgui.Col_.button.value
    button_hovered = imgui.Col_.button_hovered.value
    button_active = imgui.Col_.button_active.value
    header = imgui.Col_.header.value
    header_hovered = imgui.Col_.header_hovered.value
    header_active = imgui.Col_.header_active.value
    separator = imgui.Col_.separator.value
    separator_hovered = imgui.Col_.separator_hovered.value
    separator_active = imgui.Col_.separator_active.value
    resize_grip = imgui.Col_.resize_grip.value
    resize_grip_hovered = imgui.Col_.resize_grip_hovered.value
    resize_grip_active = imgui.Col_.resize_grip_active.value
    tab_hovered = imgui.Col_.tab_hovered.value
    tab = imgui.Col_.tab.value
    tab_selected = imgui.Col_.tab_selected.value
    tab_selected_overline = imgui.Col_.tab_selected_overline.value
    tab_dimmed = imgui.Col_.tab_dimmed.value
    tab_dimmed_selected = imgui.Col_.tab_dimmed_selected.value
    tab_dimmed_selected_overline = imgui.Col_.tab_dimmed_selected_overline.value
    docking_preview = imgui.Col_.docking_preview.value
    docking_empty_bg = imgui.Col_.docking_empty_bg.value
    plot_lines = imgui.Col_.plot_lines.value
    plot_lines_hovered = imgui.Col_.plot_lines_hovered.value
    plot_histogram = imgui.Col_.plot_histogram.value
    plot_histogram_hovered = imgui.Col_.plot_histogram_hovered.value
    table_header_bg = imgui.Col_.table_header_bg.value
    table_border_strong = imgui.Col_.table_border_strong.value
    table_border_light = imgui.Col_.table_border_light.value
    table_row_bg = imgui.Col_.table_row_bg.value
    table_row_bg_alt = imgui.Col_.table_row_bg_alt.value
    text_link = imgui.Col_.text_link.value
    text_selected_bg = imgui.Col_.text_selected_bg.value
    drag_drop_target = imgui.Col_.drag_drop_target.value
    nav_cursor = imgui.Col_.nav_cursor.value
    nav_windowing_highlight = imgui.Col_.nav_windowing_highlight.value
    nav_windowing_dim_bg = imgui.Col_.nav_windowing_dim_bg.value
    modal_window_dim_bg = imgui.Col_.modal_window_dim_bg.value
    count = imgui.Col_.count.value


TEXT: Final[int] = int(ColorVar.text)
TEXT_DISABLED: Final[int] = int(ColorVar.text_disabled)
WINDOW_BG: Final[int] = int(ColorVar.window_bg)
CHILD_BG: Final[int] = int(ColorVar.child_bg)
POPUP_BG: Final[int] = int(ColorVar.popup_bg)
BORDER: Final[int] = int(ColorVar.border)
BORDER_SHADOW: Final[int] = int(ColorVar.border_shadow)
FRAME_BG: Final[int] = int(ColorVar.frame_bg)
FRAME_BG_HOVERED: Final[int] = int(ColorVar.frame_bg_hovered)
FRAME_BG_ACTIVE: Final[int] = int(ColorVar.frame_bg_active)
TITLE_BG: Final[int] = int(ColorVar.title_bg)
TITLE_BG_ACTIVE: Final[int] = int(ColorVar.title_bg_active)
TITLE_BG_COLLAPSED: Final[int] = int(ColorVar.title_bg_collapsed)
MENU_BAR_BG: Final[int] = int(ColorVar.menu_bar_bg)
SCROLLBAR_BG: Final[int] = int(ColorVar.scrollbar_bg)
SCROLLBAR_GRAB: Final[int] = int(ColorVar.scrollbar_grab)
SCROLLBAR_GRAB_HOVERED: Final[int] = int(ColorVar.scrollbar_grab_hovered)
SCROLLBAR_GRAB_ACTIVE: Final[int] = int(ColorVar.scrollbar_grab_active)
CHECK_MARK: Final[int] = int(ColorVar.check_mark)
SLIDER_GRAB: Final[int] = int(ColorVar.slider_grab)
SLIDER_GRAB_ACTIVE: Final[int] = int(ColorVar.slider_grab_active)
BUTTON: Final[int] = int(ColorVar.button)
BUTTON_HOVERED: Final[int] = int(ColorVar.button_hovered)
BUTTON_ACTIVE: Final[int] = int(ColorVar.button_active)
HEADER: Final[int] = int(ColorVar.header)
HEADER_HOVERED: Final[int] = int(ColorVar.header_hovered)
HEADER_ACTIVE: Final[int] = int(ColorVar.header_active)
SEPARATOR: Final[int] = int(ColorVar.separator)
SEPARATOR_HOVERED: Final[int] = int(ColorVar.separator_hovered)
SEPARATOR_ACTIVE: Final[int] = int(ColorVar.separator_active)
RESIZE_GRIP: Final[int] = int(ColorVar.resize_grip)
RESIZE_GRIP_HOVERED: Final[int] = int(ColorVar.resize_grip_hovered)
RESIZE_GRIP_ACTIVE: Final[int] = int(ColorVar.resize_grip_active)
TAB_HOVERED: Final[int] = int(ColorVar.tab_hovered)
TAB: Final[int] = int(ColorVar.tab)
TAB_SELECTED: Final[int] = int(ColorVar.tab_selected)
TAB_SELECTED_OVERLINE: Final[int] = int(ColorVar.tab_selected_overline)
TAB_DIMMED: Final[int] = int(ColorVar.tab_dimmed)
TAB_DIMMED_SELECTED: Final[int] = int(ColorVar.tab_dimmed_selected)
TAB_DIMMED_SELECTED_OVERLINE: Final[int] = int(ColorVar.tab_dimmed_selected_overline)
DOCKING_PREVIEW: Final[int] = int(ColorVar.docking_preview)
DOCKING_EMPTY_BG: Final[int] = int(ColorVar.docking_empty_bg)
PLOT_LINES: Final[int] = int(ColorVar.plot_lines)
PLOT_LINES_HOVERED: Final[int] = int(ColorVar.plot_lines_hovered)
PLOT_HISTOGRAM: Final[int] = int(ColorVar.plot_histogram)
PLOT_HISTOGRAM_HOVERED: Final[int] = int(ColorVar.plot_histogram_hovered)
TABLE_HEADER_BG: Final[int] = int(ColorVar.table_header_bg)
TABLE_BORDER_STRONG: Final[int] = int(ColorVar.table_border_strong)
TABLE_BORDER_LIGHT: Final[int] = int(ColorVar.table_border_light)
TABLE_ROW_BG: Final[int] = int(ColorVar.table_row_bg)
TABLE_ROW_BG_ALT: Final[int] = int(ColorVar.table_row_bg_alt)
TEXT_LINK: Final[int] = int(ColorVar.text_link)
TEXT_SELECTED_BG: Final[int] = int(ColorVar.text_selected_bg)
DRAG_DROP_TARGET: Final[int] = int(ColorVar.drag_drop_target)
NAV_CURSOR: Final[int] = int(ColorVar.nav_cursor)
NAV_WINDOWING_HIGHLIGHT: Final[int] = int(ColorVar.nav_windowing_highlight)
NAV_WINDOWING_DIM_BG: Final[int] = int(ColorVar.nav_windowing_dim_bg)
MODAL_WINDOW_DIM_BG: Final[int] = int(ColorVar.modal_window_dim_bg)
COUNT: Final[int] = int(ColorVar.count)
