# -*- coding: utf-8 -*-

from abc import ABC, abstractmethod
from textwrap import dedent

from cvp.types.override import override


class FileTemplateInterface(ABC):
    @abstractmethod
    def generate_file_header(self) -> str:
        raise NotImplementedError

    @abstractmethod
    def generate_imports(self) -> str:
        raise NotImplementedError


class DefaultTemplate(FileTemplateInterface):
    @override
    def generate_file_header(self) -> str:
        return dedent(
            """\
            # -*- coding: utf-8 -*-
            # This file is automatically generated from the Swagger/OpenAPI spec.
            """
        )

    @override
    def generate_imports(self) -> str:
        return dedent(
            """\
            import datetime
            import json
            import typing
            import urllib.parse
            import httpx
            import pydantic
            """
        )
