# -*- coding: utf-8 -*-

from types import MappingProxyType
from typing import Final

from cvp.fonts.glyphs.mdi import (
    ALPHA_A,
    ALPHA_A_BOX_OUTLINE,
    ALPHA_B,
    ALPHA_B_BOX_OUTLINE,
    ALPHA_C,
    ALPHA_C_BOX_OUTLINE,
    ALPHA_D,
    ALPHA_D_BOX_OUTLINE,
    ALPHA_E,
    ALPHA_E_BOX_OUTLINE,
    ALPHA_F,
    ALPHA_F_BOX_OUTLINE,
    ALPHA_G,
    ALPHA_G_BOX_OUTLINE,
    ALPHA_H,
    ALPHA_H_BOX_OUTLINE,
    ALPHA_I,
    ALPHA_I_BOX_OUTLINE,
    ALPHA_J,
    ALPHA_J_BOX_OUTLINE,
    ALPHA_K,
    ALPHA_K_BOX_OUTLINE,
    ALPHA_L,
    ALPHA_L_BOX_OUTLINE,
    ALPHA_M,
    ALPHA_M_BOX_OUTLINE,
    ALPHA_N,
    ALPHA_N_BOX_OUTLINE,
    ALPHA_O,
    ALPHA_O_BOX_OUTLINE,
    ALPHA_P,
    ALPHA_P_BOX_OUTLINE,
    ALPHA_Q,
    ALPHA_Q_BOX_OUTLINE,
    ALPHA_R,
    ALPHA_R_BOX_OUTLINE,
    ALPHA_S,
    ALPHA_S_BOX_OUTLINE,
    ALPHA_T,
    ALPHA_T_BOX_OUTLINE,
    ALPHA_U,
    ALPHA_U_BOX_OUTLINE,
    ALPHA_V,
    ALPHA_V_BOX_OUTLINE,
    ALPHA_W,
    ALPHA_W_BOX_OUTLINE,
    ALPHA_X,
    ALPHA_X_BOX_OUTLINE,
    ALPHA_Y,
    ALPHA_Y_BOX_OUTLINE,
    ALPHA_Z,
    ALPHA_Z_BOX_OUTLINE,
    MINUS,
    MINUS_BOX_OUTLINE,
    NUMERIC_0,
    NUMERIC_0_BOX_OUTLINE,
    NUMERIC_1,
    NUMERIC_1_BOX_OUTLINE,
    NUMERIC_2,
    NUMERIC_2_BOX_OUTLINE,
    NUMERIC_3,
    NUMERIC_3_BOX_OUTLINE,
    NUMERIC_4,
    NUMERIC_4_BOX_OUTLINE,
    NUMERIC_5,
    NUMERIC_5_BOX_OUTLINE,
    NUMERIC_6,
    NUMERIC_6_BOX_OUTLINE,
    NUMERIC_7,
    NUMERIC_7_BOX_OUTLINE,
    NUMERIC_8,
    NUMERIC_8_BOX_OUTLINE,
    NUMERIC_9,
    NUMERIC_9_BOX_OUTLINE,
)

DTYPE_ICON_MAPPING: Final[MappingProxyType[str, str]] = MappingProxyType(
    {
        # Underscore
        "_": MINUS,
        # Numeric
        "0": NUMERIC_0,
        "1": NUMERIC_1,
        "2": NUMERIC_2,
        "3": NUMERIC_3,
        "4": NUMERIC_4,
        "5": NUMERIC_5,
        "6": NUMERIC_6,
        "7": NUMERIC_7,
        "8": NUMERIC_8,
        "9": NUMERIC_9,
        # Alpha Uppercase
        "A": ALPHA_A,
        "B": ALPHA_B,
        "C": ALPHA_C,
        "D": ALPHA_D,
        "E": ALPHA_E,
        "F": ALPHA_F,
        "G": ALPHA_G,
        "H": ALPHA_H,
        "I": ALPHA_I,
        "J": ALPHA_J,
        "K": ALPHA_K,
        "L": ALPHA_L,
        "M": ALPHA_M,
        "N": ALPHA_N,
        "O": ALPHA_O,
        "P": ALPHA_P,
        "Q": ALPHA_Q,
        "R": ALPHA_R,
        "S": ALPHA_S,
        "T": ALPHA_T,
        "U": ALPHA_U,
        "V": ALPHA_V,
        "W": ALPHA_W,
        "X": ALPHA_X,
        "Y": ALPHA_Y,
        "Z": ALPHA_Z,
        # Alpha Lowercase
        "a": ALPHA_A,
        "b": ALPHA_B,
        "c": ALPHA_C,
        "d": ALPHA_D,
        "e": ALPHA_E,
        "f": ALPHA_F,
        "g": ALPHA_G,
        "h": ALPHA_H,
        "i": ALPHA_I,
        "j": ALPHA_J,
        "k": ALPHA_K,
        "l": ALPHA_L,
        "m": ALPHA_M,
        "n": ALPHA_N,
        "o": ALPHA_O,
        "p": ALPHA_P,
        "q": ALPHA_Q,
        "r": ALPHA_R,
        "s": ALPHA_S,
        "t": ALPHA_T,
        "u": ALPHA_U,
        "v": ALPHA_V,
        "w": ALPHA_W,
        "x": ALPHA_X,
        "y": ALPHA_Y,
        "z": ALPHA_Z,
    }
)

NODE_ICON_MAPPING: Final[MappingProxyType[str, str]] = MappingProxyType(
    {
        # Underscore
        "_": MINUS_BOX_OUTLINE,
        # Numeric
        "0": NUMERIC_0_BOX_OUTLINE,
        "1": NUMERIC_1_BOX_OUTLINE,
        "2": NUMERIC_2_BOX_OUTLINE,
        "3": NUMERIC_3_BOX_OUTLINE,
        "4": NUMERIC_4_BOX_OUTLINE,
        "5": NUMERIC_5_BOX_OUTLINE,
        "6": NUMERIC_6_BOX_OUTLINE,
        "7": NUMERIC_7_BOX_OUTLINE,
        "8": NUMERIC_8_BOX_OUTLINE,
        "9": NUMERIC_9_BOX_OUTLINE,
        # Alpha Uppercase
        "A": ALPHA_A_BOX_OUTLINE,
        "B": ALPHA_B_BOX_OUTLINE,
        "C": ALPHA_C_BOX_OUTLINE,
        "D": ALPHA_D_BOX_OUTLINE,
        "E": ALPHA_E_BOX_OUTLINE,
        "F": ALPHA_F_BOX_OUTLINE,
        "G": ALPHA_G_BOX_OUTLINE,
        "H": ALPHA_H_BOX_OUTLINE,
        "I": ALPHA_I_BOX_OUTLINE,
        "J": ALPHA_J_BOX_OUTLINE,
        "K": ALPHA_K_BOX_OUTLINE,
        "L": ALPHA_L_BOX_OUTLINE,
        "M": ALPHA_M_BOX_OUTLINE,
        "N": ALPHA_N_BOX_OUTLINE,
        "O": ALPHA_O_BOX_OUTLINE,
        "P": ALPHA_P_BOX_OUTLINE,
        "Q": ALPHA_Q_BOX_OUTLINE,
        "R": ALPHA_R_BOX_OUTLINE,
        "S": ALPHA_S_BOX_OUTLINE,
        "T": ALPHA_T_BOX_OUTLINE,
        "U": ALPHA_U_BOX_OUTLINE,
        "V": ALPHA_V_BOX_OUTLINE,
        "W": ALPHA_W_BOX_OUTLINE,
        "X": ALPHA_X_BOX_OUTLINE,
        "Y": ALPHA_Y_BOX_OUTLINE,
        "Z": ALPHA_Z_BOX_OUTLINE,
        # Alpha Lowercase
        "a": ALPHA_A_BOX_OUTLINE,
        "b": ALPHA_B_BOX_OUTLINE,
        "c": ALPHA_C_BOX_OUTLINE,
        "d": ALPHA_D_BOX_OUTLINE,
        "e": ALPHA_E_BOX_OUTLINE,
        "f": ALPHA_F_BOX_OUTLINE,
        "g": ALPHA_G_BOX_OUTLINE,
        "h": ALPHA_H_BOX_OUTLINE,
        "i": ALPHA_I_BOX_OUTLINE,
        "j": ALPHA_J_BOX_OUTLINE,
        "k": ALPHA_K_BOX_OUTLINE,
        "l": ALPHA_L_BOX_OUTLINE,
        "m": ALPHA_M_BOX_OUTLINE,
        "n": ALPHA_N_BOX_OUTLINE,
        "o": ALPHA_O_BOX_OUTLINE,
        "p": ALPHA_P_BOX_OUTLINE,
        "q": ALPHA_Q_BOX_OUTLINE,
        "r": ALPHA_R_BOX_OUTLINE,
        "s": ALPHA_S_BOX_OUTLINE,
        "t": ALPHA_T_BOX_OUTLINE,
        "u": ALPHA_U_BOX_OUTLINE,
        "v": ALPHA_V_BOX_OUTLINE,
        "w": ALPHA_W_BOX_OUTLINE,
        "x": ALPHA_X_BOX_OUTLINE,
        "y": ALPHA_Y_BOX_OUTLINE,
        "z": ALPHA_Z_BOX_OUTLINE,
    }
)
