# -*- coding: utf-8 -*-
# flake8: noqa
# mypy: ignore-errors
# This file is automatically generated from the Swagger/OpenAPI spec.

import datetime
import typing
import urllib.parse

import httpx
import pydantic


class Error(pydantic.BaseModel):
    error: str


class AuthInternalUser(pydantic.BaseModel):
    user: str
    pass_: str = pydantic.Field(alias="pass")
    ips: typing.List[str]
    permissions: typing.List["AuthInternalUserPermission"]


class AuthInternalUserPermission(pydantic.BaseModel):
    action: str
    path: str


class GlobalConf(pydantic.BaseModel):
    logLevel: str
    logDestinations: typing.List[str]
    logFile: str
    sysLogPrefix: str
    readTimeout: str
    writeTimeout: str
    writeQueueSize: int
    udpMaxPayloadSize: int
    runOnConnect: str
    runOnConnectRestart: bool
    runOnDisconnect: str
    authMethod: str
    authInternalUsers: typing.List["AuthInternalUser"]
    authHTTPAddress: str
    authHTTPExclude: typing.List["AuthInternalUserPermission"]
    authJWTJWKS: str
    authJWTClaimKey: str
    api: bool
    apiAddress: str
    apiEncryption: bool
    apiServerKey: str
    apiServerCert: str
    apiAllowOrigin: str
    apiTrustedProxies: typing.List[str]
    metrics: bool
    metricsAddress: str
    metricsEncryption: bool
    metricsServerKey: str
    metricsServerCert: str
    metricsAllowOrigin: str
    metricsTrustedProxies: typing.List[str]
    pprof: bool
    pprofAddress: str
    pprofEncryption: bool
    pprofServerKey: str
    pprofServerCert: str
    pprofAllowOrigin: str
    pprofTrustedProxies: typing.List[str]
    playback: bool
    playbackAddress: str
    playbackEncryption: bool
    playbackServerKey: str
    playbackServerCert: str
    playbackAllowOrigin: str
    playbackTrustedProxies: typing.List[str]
    rtsp: bool
    rtspTransports: typing.List[str]
    rtspEncryption: str
    rtspAddress: str
    rtspsAddress: str
    rtpAddress: str
    rtcpAddress: str
    multicastIPRange: str
    multicastRTPPort: int
    multicastRTCPPort: int
    rtspServerKey: str
    rtspServerCert: str
    rtspAuthMethods: typing.List[str]
    rtmp: bool
    rtmpAddress: str
    rtmpEncryption: str
    rtmpsAddress: str
    rtmpServerKey: str
    rtmpServerCert: str
    hls: bool
    hlsAddress: str
    hlsEncryption: bool
    hlsServerKey: str
    hlsServerCert: str
    hlsAllowOrigin: str
    hlsTrustedProxies: typing.List[str]
    hlsAlwaysRemux: bool
    hlsVariant: str
    hlsSegmentCount: int
    hlsSegmentDuration: str
    hlsPartDuration: str
    hlsSegmentMaxSize: str
    hlsDirectory: str
    hlsMuxerCloseAfter: str
    webrtc: bool
    webrtcAddress: str
    webrtcEncryption: bool
    webrtcServerKey: str
    webrtcServerCert: str
    webrtcAllowOrigin: str
    webrtcTrustedProxies: typing.List[str]
    webrtcLocalUDPAddress: str
    webrtcLocalTCPAddress: str
    webrtcIPsFromInterfaces: bool
    webrtcIPsFromInterfacesList: typing.List[str]
    webrtcAdditionalHosts: typing.List[str]
    webrtcICEServers2: typing.List[typing.Dict[str, typing.Any]]
    webrtcHandshakeTimeout: str
    webrtcTrackGatherTimeout: str
    webrtcSTUNGatherTimeout: str
    srt: bool
    srtAddress: str


class PathConf(pydantic.BaseModel):
    name: str
    source: str
    sourceFingerprint: str
    sourceOnDemand: bool
    sourceOnDemandStartTimeout: str
    sourceOnDemandCloseAfter: str
    maxReaders: int
    srtReadPassphrase: str
    fallback: str
    useAbsoluteTimestamp: bool
    record: bool
    recordPath: str
    recordFormat: str
    recordPartDuration: str
    recordSegmentDuration: str
    recordDeleteAfter: str
    overridePublisher: bool
    srtPublishPassphrase: str
    rtspTransport: str
    rtspAnyPort: bool
    rtspRangeType: str
    rtspRangeStart: str
    sourceRedirect: str
    rpiCameraCamID: int
    rpiCameraSecondary: bool
    rpiCameraWidth: int
    rpiCameraHeight: int
    rpiCameraHFlip: bool
    rpiCameraVFlip: bool
    rpiCameraBrightness: float
    rpiCameraContrast: float
    rpiCameraSaturation: float
    rpiCameraSharpness: float
    rpiCameraExposure: str
    rpiCameraAWB: str
    rpiCameraAWBGains: typing.List[float]
    rpiCameraDenoise: str
    rpiCameraShutter: int
    rpiCameraMetering: str
    rpiCameraGain: float
    rpiCameraEV: float
    rpiCameraROI: str
    rpiCameraHDR: bool
    rpiCameraTuningFile: str
    rpiCameraMode: str
    rpiCameraFPS: float
    rpiCameraAfMode: str
    rpiCameraAfRange: str
    rpiCameraAfSpeed: str
    rpiCameraLensPosition: float
    rpiCameraAfWindow: str
    rpiCameraFlickerPeriod: int
    rpiCameraTextOverlayEnable: bool
    rpiCameraTextOverlay: str
    rpiCameraCodec: str
    rpiCameraIDRPeriod: int
    rpiCameraBitrate: int
    rpiCameraProfile: str
    rpiCameraLevel: str
    rpiCameraJPEGQuality: int
    runOnInit: str
    runOnInitRestart: bool
    runOnDemand: str
    runOnDemandRestart: bool
    runOnDemandStartTimeout: str
    runOnDemandCloseAfter: str
    runOnUnDemand: str
    runOnReady: str
    runOnReadyRestart: bool
    runOnNotReady: str
    runOnRead: str
    runOnReadRestart: bool
    runOnUnread: str
    runOnRecordSegmentCreate: str
    runOnRecordSegmentComplete: str


class PathConfList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["PathConf"]


class Path(pydantic.BaseModel):
    name: str
    confName: str
    source: typing.Any
    ready: bool
    readyTime: str
    tracks: typing.List[str]
    bytesReceived: int
    bytesSent: int
    readers: typing.List["PathReader"]


class PathList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["Path"]


class PathSource(pydantic.BaseModel):
    type: typing.Literal[
        "hlsSource",
        "redirect",
        "rpiCameraSource",
        "rtmpConn",
        "rtmpSource",
        "rtspSession",
        "rtspSource",
        "rtspsSession",
        "srtConn",
        "srtSource",
        "udpSource",
        "webRTCSession",
        "webRTCSource",
    ]
    id: str


class PathReader(pydantic.BaseModel):
    type: typing.Literal[
        "hlsMuxer",
        "rtmpConn",
        "rtspSession",
        "rtspsSession",
        "srtConn",
        "webRTCSession",
    ]
    id: str


class HLSMuxer(pydantic.BaseModel):
    path: str
    created: str
    lastRequest: str
    bytesSent: int


class HLSMuxerList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["HLSMuxer"]


class Recording(pydantic.BaseModel):
    name: str
    segments: typing.List["RecordingSegment"]


class RecordingList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["Recording"]


class RecordingSegment(pydantic.BaseModel):
    start: str


class RTMPConn(pydantic.BaseModel):
    id: str
    created: str
    remoteAddr: str
    state: typing.Literal["idle", "read", "publish"]
    path: str
    query: str
    bytesReceived: int
    bytesSent: int


class RTMPConnList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["RTMPConn"]


class RTSPConn(pydantic.BaseModel):
    id: str
    created: str
    remoteAddr: str
    bytesReceived: int
    bytesSent: int
    session: str


class RTSPConnList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["RTSPConn"]


class RTSPSession(pydantic.BaseModel):
    id: str
    created: str
    remoteAddr: str
    state: typing.Literal["idle", "read", "publish"]
    path: str
    query: str
    transport: str
    bytesReceived: int
    bytesSent: int
    rtpPacketsReceived: int
    rtpPacketsSent: int
    rtpPacketsLost: int
    rtpPacketsInError: int
    rtpPacketsJitter: float
    rtcpPacketsReceived: int
    rtcpPacketsSent: int
    rtcpPacketsInError: int


class RTSPSessionList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["RTSPSession"]


class SRTConn(pydantic.BaseModel):
    id: str
    created: str
    remoteAddr: str
    state: typing.Literal["idle", "read", "publish"]
    path: str
    query: str
    packetsSent: int
    packetsReceived: int
    packetsReceivedBelated: int
    packetsSentUnique: int
    packetsReceivedUnique: int
    packetsSendLoss: int
    packetsReceivedLoss: int
    packetsRetrans: int
    packetsReceivedRetrans: int
    packetsSentACK: int
    packetsReceivedACK: int
    packetsSentNAK: int
    packetsReceivedNAK: int
    packetsSentKM: int
    packetsReceivedKM: int
    usSndDuration: int
    packetsSendDrop: int
    packetsReceivedDrop: int
    packetsReceivedUndecrypt: int
    bytesSent: int
    bytesReceived: int
    bytesReceivedBelated: int
    bytesSentUnique: int
    bytesReceivedUnique: int
    bytesReceivedLoss: int
    bytesRetrans: int
    bytesReceivedRetrans: int
    bytesSendDrop: int
    bytesReceivedDrop: int
    bytesReceivedUndecrypt: int
    usPacketsSendPeriod: float
    packetsFlowWindow: int
    packetsFlightSize: int
    msRTT: float
    mbpsSendRate: float
    mbpsReceiveRate: float
    mbpsLinkCapacity: float
    bytesAvailSendBuf: int
    bytesAvailReceiveBuf: int
    mbpsMaxBW: float
    byteMSS: int
    packetsSendBuf: int
    bytesSendBuf: int
    msSendBuf: int
    msSendTsbPdDelay: int
    packetsReceiveBuf: int
    bytesReceiveBuf: int
    msReceiveBuf: int
    msReceiveTsbPdDelay: int
    packetsReorderTolerance: int
    packetsReceivedAvgBelatedTime: int
    packetsSendLossRate: float
    packetsReceivedLossRate: float


class SRTConnList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["SRTConn"]


class WebRTCSession(pydantic.BaseModel):
    id: str
    created: str
    remoteAddr: str
    peerConnectionEstablished: bool
    localCandidate: str
    remoteCandidate: str
    state: typing.Literal["read", "publish"]
    path: str
    query: str
    bytesReceived: int
    bytesSent: int


class WebRTCSessionList(pydantic.BaseModel):
    pageCount: int
    itemCount: int
    items: typing.List["WebRTCSession"]


# noinspection SpellCheckingInspection
# noinspection PyPep8Naming
# noinspection PyShadowingNames
# noinspection PyShadowingBuiltins
class MediamtxApi:
    """
    API of MediaMTX, a server and proxy that supports various protocols.
    """

    def __init__(self, base_url: str, **kwargs):
        self._client = httpx.Client(base_url=base_url, **kwargs)

    @property
    def client(self):
        return self._client

    @staticmethod
    def _tznow():
        return datetime.datetime.now().astimezone()

    @staticmethod
    def _format_path(
        path: str,
        /,
        path_kwargs: typing.Optional[typing.Dict[str, typing.Any]] = None,
        queries: typing.Optional[typing.Dict[str, typing.Any]] = None,
        *,
        quote_safe: typing.Union[str, typing.Iterable[int]] = "/",
    ) -> str:
        try:
            formatted_path = path.format(**(path_kwargs or {}))
        except KeyError as e:
            raise ValueError(f"Missing required path parameter: {e}")

        encoded_path = urllib.parse.quote(formatted_path, safe=quote_safe)
        filtered_queries = {k: v for k, v in (queries or {}).items() if v is not None}

        if query_string := urllib.parse.urlencode(filtered_queries):
            return f"{encoded_path}?{query_string}"
        else:
            return encoded_path

    def configGlobalGet(self):
        """returns the global configuration.

        Tags:
            Configuration
        """
        _method = "get"
        _path = "/v3/config/global/get"
        _path_kwargs = dict()
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return GlobalConf.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configGlobalSet(self, requestBody: GlobalConf):
        """patches the global configuration.

        all fields are optional.

        Tags:
            Configuration
        """
        _method = "patch"
        _path = "/v3/config/global/patch"
        _path_kwargs = dict()
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _content = requestBody.model_dump_json()
        _response = self._client.request(
            _method, _url, content=_content, headers=_headers
        )
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathDefaultsGet(self):
        """returns the default path configuration.

        Tags:
            Configuration
        """
        _method = "get"
        _path = "/v3/config/pathdefaults/get"
        _path_kwargs = dict()
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return PathConf.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathDefaultsPatch(self, requestBody: PathConf):
        """patches the default path configuration.

        all fields are optional.

        Tags:
            Configuration
        """
        _method = "patch"
        _path = "/v3/config/pathdefaults/patch"
        _path_kwargs = dict()
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _content = requestBody.model_dump_json()
        _response = self._client.request(
            _method, _url, content=_content, headers=_headers
        )
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all path configurations.

        Tags:
            Configuration
        """
        _method = "get"
        _path = "/v3/config/paths/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return PathConfList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathsGet(self, name: str):
        """returns a path configuration.

        Tags:
            Configuration
        """
        _method = "get"
        _path = "/v3/config/paths/get/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return PathConf.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathsAdd(self, name: str, requestBody: PathConf):
        """adds a path configuration.

        all fields are optional.

        Tags:
            Configuration
        """
        _method = "post"
        _path = "/v3/config/paths/add/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _content = requestBody.model_dump_json()
        _response = self._client.request(
            _method, _url, content=_content, headers=_headers
        )
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathsPatch(self, name: str, requestBody: PathConf):
        """patches a path configuration.

        all fields are optional.

        Tags:
            Configuration
        """
        _method = "patch"
        _path = "/v3/config/paths/patch/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _content = requestBody.model_dump_json()
        _response = self._client.request(
            _method, _url, content=_content, headers=_headers
        )
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathsReplace(self, name: str, requestBody: PathConf):
        """replaces all values of a path configuration.

        all fields are optional.

        Tags:
            Configuration
        """
        _method = "post"
        _path = "/v3/config/paths/replace/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _content = requestBody.model_dump_json()
        _response = self._client.request(
            _method, _url, content=_content, headers=_headers
        )
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def configPathsDelete(self, name: str):
        """removes a path configuration.

        Tags:
            Configuration
        """
        _method = "delete"
        _path = "/v3/config/paths/delete/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def hlsMuxersList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all HLS muxers.

        Tags:
            HLS
        """
        _method = "get"
        _path = "/v3/hlsmuxers/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return HLSMuxerList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def hlsMuxersGet(self, name: str):
        """returns a HLS muxer.

        Tags:
            HLS
        """
        _method = "get"
        _path = "/v3/hlsmuxers/get/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return HLSMuxer.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def pathsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all paths.

        Tags:
            Paths
        """
        _method = "get"
        _path = "/v3/paths/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return PathList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def pathsGet(self, name: str):
        """returns a path.

        Tags:
            Paths
        """
        _method = "get"
        _path = "/v3/paths/get/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return Path.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspConnsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all RTSP connections.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspconns/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPConnList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspConnsGet(self, id: str):
        """returns a RTSP connection.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspconns/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPConn.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspSessionsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all RTSP sessions.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspsessions/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPSessionList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspSessionsGet(self, id: str):
        """returns a RTSP session.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspsessions/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPSession.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspSessionsKick(self, id: str):
        """kicks out a RTSP session from the server.

        Tags:
            RTSP
        """
        _method = "post"
        _path = "/v3/rtspsessions/kick/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspsConnsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all RTSPS connections.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspsconns/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPConnList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspsConnsGet(self, id: str):
        """returns a RTSPS connection.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspsconns/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPConn.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspsSessionsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all RTSPS sessions.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspssessions/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPSessionList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspsSessionsGet(self, id: str):
        """returns a RTSPS session.

        Tags:
            RTSP
        """
        _method = "get"
        _path = "/v3/rtspssessions/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTSPSession.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtspsSessionsKick(self, id: str):
        """kicks out a RTSPS session from the server.

        Tags:
            RTSP
        """
        _method = "post"
        _path = "/v3/rtspssessions/kick/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtmpConnsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all RTMP connections.

        Tags:
            RTMP
        """
        _method = "get"
        _path = "/v3/rtmpconns/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTMPConnList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtmpConnectionsGet(self, id: str):
        """returns a RTMP connection.

        Tags:
            RTMP
        """
        _method = "get"
        _path = "/v3/rtmpconns/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTMPConn.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtmpConnsKick(self, id: str):
        """kicks out a RTMP connection from the server.

        Tags:
            RTMP
        """
        _method = "post"
        _path = "/v3/rtmpconns/kick/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtmpsConnsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all RTMPS connections.

        Tags:
            RTMP
        """
        _method = "get"
        _path = "/v3/rtmpsconns/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTMPConnList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtmpsConnectionsGet(self, id: str):
        """returns a RTMPS connection.

        Tags:
            RTMP
        """
        _method = "get"
        _path = "/v3/rtmpsconns/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RTMPConn.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def rtmpsConnsKick(self, id: str):
        """kicks out a RTMPS connection from the server.

        Tags:
            RTMP
        """
        _method = "post"
        _path = "/v3/rtmpsconns/kick/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def srtConnsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all SRT connections.

        Tags:
            SRT
        """
        _method = "get"
        _path = "/v3/srtconns/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return SRTConnList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def srtConnsGet(self, id: str):
        """returns a SRT connection.

        Tags:
            SRT
        """
        _method = "get"
        _path = "/v3/srtconns/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return SRTConn.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def srtConnsKick(self, id: str):
        """kicks out a SRT connection from the server.

        Tags:
            SRT
        """
        _method = "post"
        _path = "/v3/srtconns/kick/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def webrtcSessionsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all WebRTC sessions.

        Tags:
            WebRTC
        """
        _method = "get"
        _path = "/v3/webrtcsessions/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return WebRTCSessionList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def webrtcSessionsGet(self, id: str):
        """returns a WebRTC session.

        Tags:
            WebRTC
        """
        _method = "get"
        _path = "/v3/webrtcsessions/get/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return WebRTCSession.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def webrtcSessionsKick(self, id: str):
        """kicks out a WebRTC session from the server.

        Tags:
            WebRTC
        """
        _method = "post"
        _path = "/v3/webrtcsessions/kick/{id}"
        _path_kwargs = dict()
        _path_kwargs["id"] = id
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def recordingsList(
        self, page: typing.Optional[int] = 0, itemsPerPage: typing.Optional[int] = 100
    ):
        """returns all recordings.

        Tags:
            Recordings
        """
        _method = "get"
        _path = "/v3/recordings/list"
        _path_kwargs = dict()
        _queries = dict()
        _queries["page"] = page
        _queries["itemsPerPage"] = itemsPerPage
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return RecordingList.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def recordingsGet(self, name: str):
        """returns recordings for a path.

        Tags:
            Recordings
        """
        _method = "get"
        _path = "/v3/recordings/get/{name}"
        _path_kwargs = dict()
        _path_kwargs["name"] = name
        _queries = dict()
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 200:
            return Recording.model_validate(_response.json())
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response

    def recordingsDeleteSegment(self, path: str, start: str):
        """deletes a recording segment.

        Tags:
            Recordings
        """
        _method = "delete"
        _path = "/v3/recordings/deletesegment"
        _path_kwargs = dict()
        _queries = dict()
        _queries["path"] = path
        _queries["start"] = start
        _headers = dict()
        _url = self._format_path(_path, _path_kwargs, _queries)
        _response = self._client.request(_method, _url, headers=_headers)
        _status_code = _response.status_code
        if _status_code == 400:
            return Error.model_validate(_response.json())
        if _status_code == 404:
            return Error.model_validate(_response.json())
        if _status_code == 500:
            return Error.model_validate(_response.json())
        return _response
