"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Pit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DELAY_FIELD_NUMBER: builtins.int
    delay: builtins.float
    def __init__(
        self,
        *,
        delay: builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["delay", b"delay"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Pit: typing_extensions.TypeAlias = Pit

@typing.final
class Pat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ok", b"ok"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Pat: typing_extensions.TypeAlias = Pat
