# -*- coding: utf-8 -*-

from cvp.chat.queries import conversation, message, stream

CREATE_TABLE_CONVERSATION = conversation.CREATE_TABLE
CREATE_TABLE_MESSAGE = message.CREATE_TABLE
CREATE_TABLE_STREAM = stream.CREATE_TABLE

INSERT_CONVERSATION = conversation.INSERT
UPDATE_CONVERSATION_TITLE = conversation.UPDATE_TITLE
DELETE_CONVERSATION = conversation.DELETE
SELECT_CONVERSATION_LATEST = conversation.SELECT_LATEST
SELECT_CONVERSATION_LATEST_AFTER_ID = conversation.SELECT_LATEST_AFTER_ID

INSERT_MESSAGE = message.INSERT
UPDATE_MESSAGE_ERROR_STATUS = message.UPDATE_ERROR_STATUS
DELETE_MESSAGE = message.DELETE
SELECT_MESSAGE = message.SELECT

INSERT_STREAM = stream.INSERT
DELETE_STREAM = stream.DELETE
SELECT_STREAM = stream.SELECT
