# -*- coding: utf-8 -*-

from io import StringIO
from keyword import kwlist
from textwrap import indent
from typing import Optional, Union

from cvp.strings.case_converter import pascal_case
from cvp.strings.symbol_case import python_symbol_case
from cvp.swagger.annotation import openapi_schema_to_python_annotation
from cvp.swagger.schemas.v3 import (
    OpenAPIObject,
    OperationObject,
    ParameterObject,
    PathItemObject,
    ReferenceObject,
    RequestBodyObject,
    ResponseObject,
    SchemaObject,
    SchemaUnion,
)

_FILE_PREFIX_TEMPLATE = """# -*- coding: utf-8 -*-
# flake8: noqa
# mypy: ignore-errors
# This file is automatically generated from the Swagger/OpenAPI spec.

import datetime
import ssl
import typing
import urllib.parse

import httpx

# noinspection PyProtectedMember
import httpx._client as httpx_client

# noinspection PyProtectedMember
import httpx._config as httpx_config

# noinspection PyProtectedMember
import httpx._transports.base as httpx_transports

# noinspection PyProtectedMember
import httpx._types as httpx_types
import pydantic


"""

_CLIENT_CLASS_BASE_TEMPLATE = """
    def __init__(
        self,
        base_url: str,
        *,
        auth: typing.Optional[httpx_types.AuthTypes] = None,
        params: typing.Optional[httpx_types.QueryParamTypes] = None,
        headers: typing.Optional[httpx_types.HeaderTypes] = None,
        cookies: typing.Optional[httpx_types.CookieTypes] = None,
        verify: typing.Union[ssl.SSLContext, str, bool] = True,
        cert: typing.Optional[httpx_types.CertTypes] = None,
        trust_env: bool = True,
        http1: bool = True,
        http2: bool = False,
        proxy: typing.Optional[httpx_types.ProxyTypes] = None,
        mounts: typing.Optional[
            typing.Mapping[str, typing.Optional[httpx_transports.BaseTransport]]
        ] = None,
        timeout: httpx_types.TimeoutTypes = httpx_config.DEFAULT_TIMEOUT_CONFIG,
        follow_redirects: bool = False,
        limits: httpx_config.Limits = httpx_config.DEFAULT_LIMITS,
        max_redirects: int = httpx_config.DEFAULT_MAX_REDIRECTS,
        event_hooks: typing.Optional[
            typing.Mapping[str, typing.List[httpx_client.EventHook]]
        ] = None,
        transport: typing.Optional[httpx_transports.BaseTransport] = None,
        default_encoding: typing.Union[str, typing.Callable[[bytes], str]] = "utf-8",
    ):
        self._client = httpx.Client(
            auth=auth,
            params=params,
            headers=headers,
            cookies=cookies,
            verify=verify,
            cert=cert,
            trust_env=trust_env,
            http1=http1,
            http2=http2,
            proxy=proxy,
            mounts=mounts,
            timeout=timeout,
            follow_redirects=follow_redirects,
            limits=limits,
            max_redirects=max_redirects,
            event_hooks=event_hooks,
            base_url=base_url,
            transport=transport,
            default_encoding=default_encoding,
        )

    @property
    def client(self):
        return self._client

    @staticmethod
    def _tznow():
        return datetime.datetime.now().astimezone()

    @staticmethod
    def _format_path(
        path: str,
        /,
        path_kwargs: typing.Optional[typing.Dict[str, typing.Any]] = None,
        queries: typing.Optional[typing.Dict[str, typing.Any]] = None,
        *,
        quote_safe: typing.Union[str, typing.Iterable[int]] = "/",
    ) -> str:
        try:
            formatted_path = path.format(**(path_kwargs or {}))
        except KeyError as e:
            raise ValueError(f"Missing required path parameter: {e}")

        encoded_path = urllib.parse.quote(formatted_path, safe=quote_safe)
        filtered_queries = {k: v for k, v in (queries or {}).items() if v is not None}

        if query_string := urllib.parse.urlencode(filtered_queries):
            return f"{encoded_path}?{query_string}"
        else:
            return encoded_path

"""


class HttpxClientGenerator:
    def __init__(self, spec: OpenAPIObject):
        self._spec = spec

    def generate(
        self,
        class_name: Optional[str] = None,
        description: Optional[str] = None,
        black_formatting: Optional[bool] = None,
    ) -> str:
        buffer = StringIO()
        buffer.write(_FILE_PREFIX_TEMPLATE)

        if self._spec.components is not None:
            for schema_name in self._spec.components.schemas or {}:
                schema = self._spec.components.schemas[schema_name]
                if isinstance(schema, SchemaObject):
                    buffer.write(self._generate_schema_class(schema_name, schema))
                else:
                    raise TypeError(f"Unsupported schema type: {type(schema).__name__}")

        client_prefix = self._generate_client_prefix(
            class_name=class_name,
            description=description,
        )
        buffer.write(client_prefix)

        if self._spec.paths is not None:
            for path in self._spec.paths.root or {}:
                path_item = self._spec.paths.root[path]
                buffer.write(self._generate_path_methods(path, path_item))

        result = buffer.getvalue()
        if black_formatting is None:
            if self._has_black():
                return self._format_black(result)
            else:
                return result

        if black_formatting:
            return self._format_black(result)
        else:
            return result

    @staticmethod
    def _has_black() -> bool:
        try:
            import black

            return True
        except ImportError:
            return False

    @staticmethod
    def _format_black(content: str) -> str:
        from black import Mode, format_str

        return format_str(content, mode=Mode())

    @staticmethod
    def _generate_schema_class(class_name: str, schema: SchemaObject) -> str:
        buffer = StringIO()

        if schema.type != "object":
            raise ValueError(f"Unsupported schema object type: {schema.type}")

        buffer.write(f"class {class_name}(pydantic.BaseModel):\n")
        for prop_key, prop_val in (schema.properties or {}).items():
            if not isinstance(prop_val, SchemaObject):
                raise TypeError(
                    f"Unsupported '{prop_key}' property type: {type(prop_val).__name__}"
                )

            annotation = openapi_schema_to_python_annotation(prop_val)

            if prop_key in kwlist:
                buffer.write(f"    {prop_key}_: {annotation}")
                buffer.write(f' = pydantic.Field(alias="{prop_key}")\n')
            else:
                buffer.write(f"    {prop_key}: {annotation}\n")
        buffer.write("\n\n")

        return buffer.getvalue()

    def _generate_client_prefix(
        self,
        class_name: Optional[str] = None,
        description: Optional[str] = None,
    ) -> str:
        if class_name is None:
            class_name = pascal_case(self._spec.info.title)
        assert isinstance(class_name, str)
        assert class_name

        if description is None:
            description = self._spec.info.description or str()
        assert isinstance(description, str)

        buffer = StringIO()
        buffer.write("# noinspection SpellCheckingInspection\n")
        buffer.write("# noinspection PyPep8Naming\n")
        buffer.write("# noinspection PyShadowingNames\n")
        buffer.write("# noinspection PyShadowingBuiltins\n")
        buffer.write(f"class {class_name}:\n")
        if description:
            buffer.write('    """\n')
            buffer.write(f"    {description.strip()}\n")
            buffer.write('    """\n')
        buffer.write(_CLIENT_CLASS_BASE_TEMPLATE)
        return buffer.getvalue()

    def _generate_path_methods(self, path: str, path_item: PathItemObject) -> str:
        buffer = StringIO()
        for method, operation in path_item.operations.items():
            if operation is None:
                continue
            method_code = self._generate_operation_method(path, method, operation)
            buffer.write(method_code)
            buffer.write("\n")
        return buffer.getvalue()

    @staticmethod
    def _generate_schema_annotation_with_default(
        schema: Optional[SchemaUnion] = None,
        required: Optional[bool] = None,
    ) -> str:
        if schema is None:
            if required:
                return "typing.Any"
            else:
                return "typing.Any = None"

        if isinstance(schema, SchemaObject):
            annotation = openapi_schema_to_python_annotation(schema)
            default = schema.default
        elif isinstance(schema, ReferenceObject):
            if not schema.ref.startswith("#/components/schemas/"):
                raise ValueError(f"Unsupported ref value: '{schema.ref}'")
            annotation = schema.ref.removeprefix("#/components/schemas/")
            default = None
        else:
            assert False, "Inaccessible section"

        if required:
            if default is not None:
                return f"{annotation}={default}"
            else:
                return annotation

        default_text = str(default) if default is not None else "None"
        return f"typing.Optional[{annotation}] = {default_text}"

    def _generate_parameter_annotation_with_default(
        self,
        param: ParameterObject,
    ) -> str:
        schema = param.schema_
        required = param.required
        return self._generate_schema_annotation_with_default(schema, required)

    def _generate_request_annotation_with_default(
        self,
        request: Union[RequestBodyObject, ReferenceObject],
    ) -> str:
        if not isinstance(request, RequestBodyObject):
            raise TypeError(f"Unsupported request type: {type(request).__name__}")

        if "application/json" not in request.content:
            raise ValueError("Only 'application/json' is supported.")

        schema = request.content["application/json"].schema_
        required = request.required
        return self._generate_schema_annotation_with_default(schema, required)

    @staticmethod
    def _generate_response_component(
        response: Union[ResponseObject, ReferenceObject],
    ) -> str:
        if not isinstance(response, ResponseObject):
            raise TypeError(f"Unsupported response type: {type(response).__name__}")

        if response.content and "application/json" not in response.content:
            raise ValueError("Only 'application/json' is supported.")

        schema = response.content["application/json"].schema_
        if not isinstance(schema, ReferenceObject):
            raise TypeError(f"Unsupported response schema: {type(schema).__name__}")

        if not schema.ref.startswith("#/components/schemas/"):
            raise ValueError(f"Unsupported ref value: '{schema.ref}'")

        return schema.ref.removeprefix("#/components/schemas/")

    def _generate_operation_method(
        self,
        path: str,
        method: str,
        operation: OperationObject,
    ) -> str:
        function_name = operation.operationId or method + "_" + path
        assert isinstance(function_name, str)
        function_symbol = python_symbol_case(function_name)

        parameters_buffer = StringIO()
        path_params = dict()
        query_params = dict()
        header_params = dict()
        cookie_params = dict()

        for param in operation.parameters or []:
            if not isinstance(param, ParameterObject):
                raise TypeError(f"Unsupported parameter type: {type(param).__name__}")

            param_annotation = self._generate_parameter_annotation_with_default(param)
            parameters_buffer.write(f", {param.name}: {param_annotation}")

            param_key = python_symbol_case(param.name)
            match param.in_:
                case "path":
                    path_params[param_key] = param.name
                case "query":
                    query_params[param_key] = param.name
                case "header":
                    header_params[param_key] = param.name
                case "cookie":
                    cookie_params[param_key] = param.name
                case _:
                    raise ValueError(f"Unknown parameter location: {param.in_}")

        if operation.requestBody:
            request_annotation = self._generate_request_annotation_with_default(
                operation.requestBody,
            )
            parameters_buffer.write(f", requestBody: {request_annotation}")

        code = StringIO()
        code.write(f"    def {function_symbol}(self")
        code.write(parameters_buffer.getvalue())
        code.write("):\n")

        if operation.summary or operation.description:
            code.write('        """')
            if operation.summary:
                code.write(operation.summary)
                code.write("\n")
            if operation.description:
                code.write("\n")
                code.write(indent(operation.description.strip(), " " * 8))
                code.write("\n")
            if operation.tags:
                code.write("\n")
                code.write("        Tags:\n")
                for tag in operation.tags:
                    code.write(f"            {tag}\n")
            code.write('        """\n')

        code.write(f'        _method = "{method}"\n')
        code.write(f'        _path = "{path}"\n')
        code.write("        _path_kwargs = dict()\n")
        for path_key, path_param in path_params.items():
            code.write(f'        _path_kwargs["{path_param}"] = {path_key}\n')
        code.write("        _queries = dict()\n")
        for query_key, query_param in query_params.items():
            code.write(f'        _queries["{query_param}"] = {query_key}\n')
        code.write("        _headers = dict()\n")
        for header_key, header_param in header_params.items():
            code.write(f'        _headers["{header_param}"] = {header_key}\n')
        code.write("        _url = self._format_path(_path, _path_kwargs, _queries)\n")
        if operation.requestBody:
            code.write("        _body = requestBody.model_dump_json()\n")
            code.write('        _headers["Content-Type"] = "application/json"\n')
        code.write("        _response = self._client.request(_method, _url")
        if operation.requestBody:
            code.write(", content=_body")
        code.write(", headers=_headers)\n")
        code.write(f"        _status_code = _response.status_code\n")

        if operation.responses:
            for status_code in operation.responses.list_status_codes():
                response_object = operation.responses.get_status_code(status_code)
                if response_object is None:
                    continue

                try:
                    component = self._generate_response_component(response_object)
                    code.write(f"        if _status_code == {int(status_code)}:\n")
                    code.write(f"            return {component}")
                    code.write(".model_validate(_response.json())\n")
                except:  # noqa
                    pass

        code.write("        return _response\n")
        return code.getvalue()
