# -*- coding: utf-8 -*-

from io import StringIO
from keyword import kwlist
from typing import Optional

from cvp.strings.case_converter import pascal_case
from cvp.swagger.schemas.v3 import OpenAPIObject, PathItemObject, SchemaObject
from cvp.swagger.types import openapi_type_to_python_annotation

_FILE_PREFIX_TEMPLATE = """# -*- coding: utf-8 -*-
# This file is automatically generated from the Swagger/OpenAPI spec.

import datetime
import json
import typing
import urllib.parse

import httpx
import pydantic


"""

_CLIENT_CLASS_PREFIX_TEMPLATE = """class {class_name}:
    \"\"\"
    {description}
    \"\"\"

    def __init__(self, base_url: str, **kwargs):
        self._client = httpx.Client(base_url=base_url, **kwargs)

    @property
    def client(self):
        return self._client
"""


class HttpxClientGenerator:
    def __init__(self, spec: OpenAPIObject):
        self._spec = spec

    def generate(
        self,
        class_name: Optional[str] = None,
        description: Optional[str] = None,
    ) -> str:
        buffer = StringIO()
        buffer.write(_FILE_PREFIX_TEMPLATE)

        if self._spec.components is not None:
            for schema_name in self._spec.components.schemas or {}:
                schema = self._spec.components.schemas[schema_name]
                if isinstance(schema, SchemaObject):
                    buffer.write(self._generate_schema_class(schema_name, schema))
                else:
                    raise TypeError(f"Unsupported schema type: {type(schema).__name__}")

        client_prefix = self._generate_client_prefix(
            class_name=class_name,
            description=description,
        )
        buffer.write(client_prefix)

        if self._spec.paths is not None:
            for path in self._spec.paths.root or {}:
                path_item = self._spec.paths.root[path]
                buffer.write(self._generate_path_method(path, path_item))

        return buffer.getvalue()

    @staticmethod
    def _generate_schema_class(class_name: str, schema: SchemaObject) -> str:
        buffer = StringIO()

        if schema.type == "object":
            buffer.write(f"class {class_name}(pydantic.BaseModel):\n")
            for prop_key, prop_val in (schema.properties or {}).items():
                annotation = openapi_type_to_python_annotation(
                    openapi_type=prop_val.type,
                    openapi_format=prop_val.format,
                    openapi_items=prop_val.items,
                )
                if prop_key in kwlist:
                    buffer.write(f"    {prop_key}_: {annotation}")
                    buffer.write(f' = pydantic.Field(alias="{prop_key}")\n')
                else:
                    buffer.write(f"    {prop_key}: {annotation}\n")
            buffer.write("\n\n")
        else:
            raise TypeError(f"Unsupported schema type: {type(schema).__name__}")

        return buffer.getvalue()

    def _generate_client_prefix(
        self,
        class_name: Optional[str] = None,
        description: Optional[str] = None,
    ) -> str:
        if class_name is None:
            class_name = pascal_case(self._spec.info.title)
        assert isinstance(class_name, str)
        assert class_name

        if description is None:
            description = self._spec.info.description or str()
        assert isinstance(description, str)

        return _CLIENT_CLASS_PREFIX_TEMPLATE.format(
            class_name=class_name,
            description=description,
        )

    @staticmethod
    def _generate_path_method(path: str, path_item: PathItemObject) -> str:
        buffer = StringIO()
        return buffer.getvalue()
